### ISSUE TITLE
model.Hall skal fixes

### ISSUE THREAD

**Issue by jakobferdinandsen** [huesimon/BioTrio#1]
Umiddelbart opstår null-pointeren i jeres model.Hall klasse. Den indeholder både hallNumber og hall_id. HallCatalog bruger Hall.getHallName() som bliver sat til det forkerte af HallCatalog.queryHall() på linje 45 når den bruger den lidt ødelagte constructor i Hall.

Umiddelbart skal Hall.getHallName() bare returnere hall_id men det ville nok være bedre at fixe Hall() constructoren på linje 67 & brugen af den constructor i HallCatalog på linje 45

**Comment by huesimon** [comment]
https://github.com/huesimon/BioTrio/commit/8474dbb118e0209c8a310f1deb7d5ee518cdae98

**Comment by huesimon** [comment]
Det ser ud til at date ikke bliver fundet i "Showing showing = new Showing(hallCatalog.getHallById(hallNum), movieCatalog.getMovieById(movie), ticketCatalog.getTicketByShowingId(showing_id), date);"

**Comment by huesimon** [comment]
![image](https://cloud.githubusercontent.com/assets/1985440/20621594/68a845fa-b2ff-11e6-8ccf-2984ed3c5a5b.png)

**Comment by huesimon** [comment]
https://github.com/huesimon/BioTrio/commit/c49af4e045e28ebae6ce5ce29a1641e6020687d1
